/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.employeeproject.forms;

import com.employeeproject.entities.Employee;
import com.employeeproject.database.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu extends javax.swing.JFrame {
    
    IDatabaseOperation iDatabaseOperation = new MySqlDatabaseOperation();
    DefaultTableModel model;
    
    Date date = new Date();
    public Menu() {
        initComponents();
        model = (DefaultTableModel)table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        telNumber = new javax.swing.JTextField();
        eMail = new javax.swing.JTextField();
        tcNumber = new javax.swing.JTextField();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        city = new javax.swing.JComboBox<>();
        adress = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        dowloadButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        working = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuEmployeeDelete = new javax.swing.JMenuItem();
        operationHistory = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuLogOut = new javax.swing.JMenuItem();

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\baris\\Documents\\NetBeansProjects\\EmployeProject\\Project Files\\background.png")); // NOI18N

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBounds(new java.awt.Rectangle(170, 145, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Soyisim");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 80, 87, 31));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Isim");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 28, 87, 31));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Dogum Tarihi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 80, 86, 31));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Telefon No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 132, 87, 31));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("E Mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 181, 87, 31));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("TC Kimlik");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 28, 86, 31));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Adres Bilgileri");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 132, -1, 31));

        name.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 32, 159, -1));

        surname.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 84, 159, -1));

        telNumber.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(telNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 136, 159, -1));

        eMail.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(eMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 185, 159, -1));

        tcNumber.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tcNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 32, 159, -1));

        day.setForeground(new java.awt.Color(204, 204, 204));
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 83, -1, -1));

        month.setForeground(new java.awt.Color(204, 204, 204));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocak", "Subat", "Mart", "Nisan", "Mayis", "Haziran", "Temmuz", "Agustos", "Eylul", "Ekim", "Kasim", "Aralik" }));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 83, -1, -1));

        year.setForeground(new java.awt.Color(204, 204, 204));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", " " }));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 83, 79, -1));

        city.setForeground(new java.awt.Color(204, 204, 204));
        city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman", "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce" }));
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 135, 109, -1));

        adress.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 172, 231, 40));

        department.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 32, 159, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Departman");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 31, 76, 24));

        salary.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 84, 159, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Maas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 83, 76, 24));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Id");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 135, 76, 24));

        id.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 136, 159, -1));

        dowloadButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dowloadButton.setText("Calisanlari Listele- Yenile");
        dowloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dowloadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dowloadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isim", "Soyisim", "Telefon", "E Mail", "TC No", "Dogum Tarihi", "Sehir", "Departman", "Maas", "Id", "Calisma S."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(7).setResizable(false);
            table.getColumnModel().getColumn(8).setResizable(false);
            table.getColumnModel().getColumn(9).setResizable(false);
            table.getColumnModel().getColumn(10).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 271, 1520, 483));

        addButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addButton1.setForeground(new java.awt.Color(0, 0, 0));
        addButton1.setText("Ekle");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(addButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1264, 78, 92, 34));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 80));

        working.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        working.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remote", "Free Lance", "Normal", "Part Time" }));
        getContentPane().add(working, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 100, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Calisma Sekli");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 90, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\baris\\Documents\\NetBeansProjects\\EmployeProject\\Project Files\\background2.png")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 600));

        jMenu1.setText("Islemler");

        menuEmployeeDelete.setText("Calisan Sil");
        menuEmployeeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmployeeDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(menuEmployeeDelete);

        operationHistory.setText("Islem Gecmisi");
        operationHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationHistoryActionPerformed(evt);
            }
        });
        jMenu1.add(operationHistory);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sistem");

        menuInfo.setText("Hakkinda");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        jMenu2.add(menuInfo);

        jMenuItem2.setText("Cikis Yap");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        menuLogOut.setText("Programi Kapat");
        menuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogOutActionPerformed(evt);
            }
        });
        jMenu2.add(menuLogOut);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void load(){
        model.setRowCount(0);
        ArrayList<Employee> employees = new ArrayList<Employee>();
        employees = iDatabaseOperation.searchEmplooye();
        
        if(employees != null){
            
            for(Employee temp: employees){
                Object[] add = {temp.getName(), temp.getSurname(), temp.getTelNo(), temp.geteMail(), temp.getTcNo(), temp.getBirthday(), temp.getAdress(), temp.getDepartment(), temp.getSalary(), temp.getId(), temp.getWorking()};
                model.addRow(add);
            }                 
        }
        
    }
   
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String datee = date.toString();
        
        Login login = new Login();
        setVisible(false);
        login.setVisible(true);
        iDatabaseOperation.loging(datee, "Login Ekranina Donuldu");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        String nameF = name.getText();
        String surnameF = surname.getText();
        String telNoF = telNumber.getText();
        String eMailF = eMail.getText();
        String tcNumberF = tcNumber.getText();
        String dayF = String.valueOf(day.getSelectedItem());
        String monthF = String.valueOf(month.getSelectedItem());
        String yearF = String.valueOf(year.getSelectedItem());
        String cityF = String.valueOf(city.getSelectedItem());
        String adressF = adress.getText();
        String departmentF = department.getText();
        String salaryF = salary.getText();
        String idF = id.getText();
        String workF = String.valueOf(working.getSelectedItem());
        
        String message = "Lutfen Bilgileri Eksiksiz Giriniz";
        
        if(nameF.isEmpty() && surnameF.isEmpty()){
            JOptionPane.showMessageDialog(this, message);
        }
        else if(telNoF.isEmpty() && eMailF.isEmpty()){
            JOptionPane.showMessageDialog(this, message);
        }
        else if(tcNumberF.isEmpty() && adressF.isEmpty()){
            JOptionPane.showMessageDialog(this, message);
        }
        else if(departmentF.isEmpty() && salaryF.isEmpty()){
            JOptionPane.showMessageDialog(this, message);
        }
        else if(idF.isEmpty()){
            JOptionPane.showMessageDialog(this, message);
        }
        else{
            String datee = date.toString();          
            iDatabaseOperation.addEmplooye(nameF, surnameF, telNoF, eMailF, tcNumberF, dayF, monthF, yearF, cityF, adressF, departmentF, salaryF, idF, workF);
            iDatabaseOperation.loging(datee, idF + " Id Numarali Calisan Eklendi");
            JOptionPane.showMessageDialog(this, "Kayit Eklendi");
            name.setText("");
            surname.setText("");
            telNumber.setText("");
            eMail.setText("");
            tcNumber.setText("");
            adress.setText("");
            department.setText("");
            salary.setText("");
            id.setText("");           
        }
        
    }//GEN-LAST:event_addButton1ActionPerformed

    private void menuEmployeeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmployeeDeleteActionPerformed
        DeleteEmployee deleteEmployee = new DeleteEmployee();
        deleteEmployee.setVisible(true);
    }//GEN-LAST:event_menuEmployeeDeleteActionPerformed

    private void menuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogOutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuLogOutActionPerformed

    private void dowloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dowloadButtonActionPerformed
        load();
    }//GEN-LAST:event_dowloadButtonActionPerformed

    private void operationHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationHistoryActionPerformed
        OperationHistory operationHistory = new OperationHistory();
        operationHistory.setVisible(true);
        
    }//GEN-LAST:event_operationHistoryActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_menuInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton1;
    private javax.swing.JTextField adress;
    private javax.swing.JComboBox<String> city;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField department;
    private javax.swing.JButton dowloadButton;
    private javax.swing.JTextField eMail;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuEmployeeDelete;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JMenuItem menuLogOut;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField name;
    private javax.swing.JMenuItem operationHistory;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField surname;
    private javax.swing.JTable table;
    private javax.swing.JTextField tcNumber;
    private javax.swing.JTextField telNumber;
    private javax.swing.JComboBox<String> working;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
